# Gunicorn configuration
workers = 4
worker_class = 'gthread'
threads = 2
worker_connections = 1000
timeout = 120
keepalive = 5
bind = '0.0.0.0:10000'
accesslog = '-'
errorlog = '-'
chdir = '/opt/render/project/src'
