services:
  - type: web
    name: finquery
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py "hackrx_llm.webapp:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true

  # Uncomment and configure if you need a database
  # - type: postgres
  #   name: finquery-db
  #   plan: free
  #   diskSize: 1GB
