services:
  # Main web application
  - type: web
    name: finquery
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py "hackrx_llm.webapp:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: GROQ_API_KEY
        sync: false  # Will be set in Render dashboard
      - key: API_AUTH_TOKEN
        sync: false  # Will be set in Render dashboard
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true

  # Webhook service
  - type: web
    name: finquery-webhook
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m hackrx_llm.webhook
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: GROQ_API_KEY
        sync: false  # Will be set in Render dashboard
      - key: API_AUTH_TOKEN
        sync: false  # Will be set in Render dashboard
    plan: free
    numInstances: 1
    healthCheckPath: /health
    autoDeploy: true
